package logtype

const (
	HF_USER_REQUEST_API       = "hf_user_request_api"
	HF_USER_HUNT_GUARDIAN_LOG = "hf_user_hunt_guardian_log"
	HF_USER_GIFT_CODE_LOG     = "hf_user_gift_code_log"
	HF_USER_ARENA_SHOP_LOG    = "hf_user_arena_shop_log"
)
const (
	UPGRADE_LEVEL_PET  = 1 //Todo item_id(string), kind_id(uint)
	UPGRADE_EVOLVE_PET = 2
	UPGRADE_INSERT_PET = 3
	UPGRADE_STAR_PET   = 4

	//UPGRADE_ENHANCE_PET uint16 = 5
	SIGN_UP = 5

	GIFT_WIN_BOSS  = 6
	GIFT_EXPLORE   = 7
	SELL_EQUIP_PET = 8 //equip_id, quantity

	UPGRADE_EQUIP_PET     = 9  //equip_id, next_id
	MATERIAL_UPGRADED_PET = 10 //equip_id, next_id

	BUY_TICKET_ARENA    = 11
	PIECE_COMBINE_PIECE = 12
	PIECE_COMBINE_PET   = 13

	GIFT_EXPLORE_BOX = 14

	FIND_RIVAL_ARENA     = 15
	INCREASE_POWER_TOWER = 16
	BUY_POWER_TOWER      = 17
	GIFT_WIN_TOWER       = 18
	USE_GAME_TOWER       = 19

	GET_DAY_TICKET_ARENA_PVP = 20
	BUY_TICKET_ARENA_PVP     = 21
	GIFT_ENDGAME_ARENA       = 22
	GIFT_ENDGAME_ARENA_PVP   = 23

	GIFT_SUMMON1_TURN = 24
	GIFT_SUMMON2_TURN = 25
	GIFT_SUMMON3_TURN = 26
	GIFT_SUMMON1_FREE = 27
	GIFT_SUMMON2_FREE = 28
	BUY_GIFT_SUMMON1  = 29
	BUY_GIFT_SUMMON2  = 30
	BUY_GIFT_SUMMON3  = 31

	GIFT_MISSION_DAILY     = 32
	GIFT_BIG_MISSION_DAILY = 33

	UPGRADE_SKILL_PET = 34
	GIFT_LEVEL_UP     = 35
	GIFT_ROLL_UP      = 36
	GIFT_NEWBIE       = 37

	GIFT_MISSION_NEWBIE     = 38
	GIFT_BIG_MISSION_NEWBIE = 39

	UPGRADE_MAX_LEVEL_PET = 40

	GIFT_EVENT_INBOX  = 41
	GIFT_EVENT        = 42
	BUY_EVENT         = 43
	GIFT_SUMMON3_FREE = 44

	GET_INFO_TICKET_GUARDIAN  = 45
	STARTGAME_TICKET_GUARDIAN = 46

	PAYMENT       = 47
	PAYMENT_BONUS = 48

	EXCHANGE_GOLD = 49

	GET_INFO_TICKET_MARKET_BLACK     = 50
	RESET_MARKET_TICKET_MARKET_BLACK = 51
	BUY_MARKET_BLACK                 = 52

	ENDGAME_GUARDIAN       = 53
	KILL_GUARDIAN          = 54
	BUY_TICKET_GUARDIAN    = 55
	COMBINE_GUARDIAN       = 56
	UPDRADE_LEVEL_GUARDIAN = 57
	EVOLVE_GUARDIAN        = 58
	PASSIVE_LEVEL_GUARDIAN = 59

	REMANE    = 60
	GIFT_CODE = 61

	SEPARATE_PIECE = 62
	UPDRADE_RUNE   = 63
	RESET_RUNE     = 64

	BUY_ARENA_SHOP             = 65
	RESET_ARENA_SHOP           = 66
	GIFT_ARENA_RANK_DAILY      = 67
	GIFT_ARENA_RANK_WEEKLY     = 68
	GIFT_ARENA_PVP_RANK_WEEKLY = 69

	GIFT_TIME = 70
)
